### ISSUE TITLE
Black cube?

### ISSUE THREAD

**Issue by jelmani** [cisc3620/7-texturing#4]
@rivlev 
Is this what I should be seeing initially before I make any changes? I'm on the texture branch
<img width="598" alt="screen shot 2017-04-26 at 7 16 48 pm" src="https://cloud.githubusercontent.com/assets/14169947/25461101/1317772c-2ab5-11e7-8dc1-421882a4838b.png">

**Comment by rivlev** [comment]
I posted a before clip of the texture program to the class website
http://www.sci.brooklyn.cuny.edu/~levitan/cisc3620/materials/hw-before.mov

Make sure you have the bunny texture in the location the program expects or point the code to where you have it. (See the updated readme.)

**Comment by dancohengtr** [comment]
Having the same issue. I've looked all around the code to try and change the directory path for the image and still nothing. The glTexImage2D function seems to be the only thing that takes the image variable as an argument. I checked the openGL tutorials site and his source code seems to be pretty much all the same except he's using the SOIL.h library header instead of the the stbi library for loading in the texture. Not sure where to go from here.

**Comment by amenak** [comment]
@dancohengtr i had the same issue. writing the full path from the C drive worked for me. It kept saying "can't fopen" in the black window that pops up with the Glitter.exe. If you get the same error, it's definitely the file path. Also make sure to use forward slash. 

For Example: 
unsigned char* image = stbi_load("C:/CISC3620/Labs/7-texturing-amenak/Textures/bunny.jpg", &w, &h, &comp, STBI_rgb);

**Comment by dancohengtr** [comment]
@amenak  that helped! It seemed to have found the file when I wrote the path starting from /Users.

**Comment by jelmani** [comment]
Yup, using the full path solved the problem, thanks guys

**Comment by DenisBarabanov** [comment]
what file do i change that in, cant seem to find it @amenak
